config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :attendences
  end
  resources :users, only: [:show]
  resources :charges
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
    after_create :event_send

    belongs_to :attendee, class_name: 'User'
    belongs_to :event

    def event_send
        EventMailer.event_email(self.attendee, self.event, self.event.admin).deliver_now
    end

end

app/models/event.rb
class Event < ApplicationRecord
    
    belongs_to :admin, class_name: 'User'
    has_many :attendences
    has_many :attendees, through: :attendences

    # validates :start_date, presence: true
    # validates :start_date_in_future

    # validates :duration, presence: true
    # validates :duration_multiple_of_five

    # validates :title, presence: true, length: {minimum: 5, maximum: 140}
    # validates :description, presence: true, length: {in: 20..1000}

    # validates :price, presence: true


    # validates :location, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    after_create :welcome_send
    
    has_many :attendences, foreign_key: 'attendee_id'
    has_many :attendees, through: :attendances
    has_many :events, foreign_key: 'admin_id'

    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller? 
    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:first_name, :last_name])
    end

private

  def require_login
    unless current_user
      redirect_to new_user_registration_path
    end
  end

end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
    def new
        @event = Event.find(params[:event_id])
    end

    def create
        @event = Event.find(params[:event_id])
        @amount = @event.price * 100
        
     
        customer = Stripe::Customer.create(
          :email => params[:stripeEmail],
          :source  => params[:stripeToken]
        )
     
        charge = Stripe::Charge.create(
          :customer    => customer.id,
          :amount      => @amount,
          :description => 'Rails Stripe customer',
          :currency    => 'usd'
        )
     
        Attendence.create(attendee: current_user, event: Event.find(params[:event_id]), stripe_customer_id: params[:stripeToken])
        redirect_to charges_path
     
        rescue Stripe::CardError => e
          flash[:error] = e.message
          redirect_to new_event_attendance_path(params[:event_id])
     end

    def index
        @event = Event.find(params[:event_id])
        @current_user = current_user
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
     
    end
    
    def create
      # Amount in cents
      @amount = 500
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    def index
      
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :edit, :update]
  def create
    @user = current_user
    @event = Event.new(title: params["title"].capitalize, description: params["description"], price: params["price"],
    admin: @user, location: params["location"].capitalize, start_date: params["start_date"])

    if @event.save
        redirect_to root_path
    else @event.errors.any?
        render :new
    end

  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(title: params["title"], start_date: params["start_date"], description: params["description"], 
      duration: params["duration"], location: params["location"], price: params["price"], admin: current_user)
      redirect_to event_path(params[:id])
    else
      redirect_to edit_event_path(params[:id])
    end
  end

  def show
    @event = Event.find(params[:id])
  end
  

  def destroy
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new 
    end

    def create
        @user = User.create(email: params["email"], password: params["password"], first_name: params["first_name"], 
        last_name: params["last_name"])

        if @user.save
            redirect_to root_path
        else @user.errors.any?
            render :new
        end
    end
    
    def show 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendences/index.html.erb
<div class="container my-5">
        <div class="row">
        <div class="col-4">
    </div>
        <div class="col-4">
<div class="card text-center bg-light">
  <div class="card-header">
    👉 YOUR EVENT 👈
  </div>
<div class="card-body">
    <h5 class="card-title font-size large"><%= @event.title %> </h5>
    <h5 class="card-title font-size: 10px"><%= @event.description %></h5>
    <h5 class="card-title font-size: 10px">Price: <%= @event.price %> $</h5>
    <h5 class="card-title font-size small">Creator: <%= @current_user.first_name %></h5>
    <h5 class="card-title font-size: 10px">Where?: <%= @event.location %>
    <h5 classe="card-title font-size: 10px">Attandees: <%= Attendence.where(event_id:(params[:id])).count %></h5>
    <h6 class="card-title font-size: 10px"><%= @event.created_at %></h6>
</div>
   <div class="col-4">
  </div>
</div>

app/views/attendences/new.html.erb
<div class="row justify-content-center text-center" style="margin-top: 10vh">
<div class="col-6">

<%= form_tag event_attendences_path(params[:event_id]), :method => :post do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <label class="amount">
      <span class="lora-regular">Your reservation for the event</span><br/>
      <h3 class="montserrat-light"><%= @event.title %></h3>
      <hr/>
      <span class="lora-regular">Amount to pay:</span><br/>
      	<span class="display-1"><%= @event.price %> $</span>
    </label>
  </article>

		  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="Your reservation for the event <%= @event.title %>"
		          data-amount="<%= @stripe_price %>"
                data-currency="usd"
		          data-locale="auto">
		  </script>


<% end %>
</div>
</div>

app/views/charges/index.html.erb
<h2>Thanks, you paid <strong><%= @event_price %> $</strong>!</h2>
<p><a class="btn btn-dark" <%= link_to "Back Home", root_path %> &raquo;</a></p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="row justify-content-center align-items-center" style="margin-top: 10vh; margin-bottom: 10vh;">
​
  <div class="col-md-8 col-sm-12">
​
    <%= form_tag url_for(action: 'update'), method: "put" do %>
      <div class="form-group">
        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', "#{@event.title}", :class => "form-control" %>
      </div>
​
      <div class="form-group">
        <%= label_tag 'Description' %>
        <%= text_area_tag 'description', "#{@event.description}", :class => "form-control", :rows => "4" %>
      </div>
​
      <div class="form-group">
        <%= label_tag 'Start Date' %>
        <%= date_field_tag 'start_date', "#{@event.start_date}", :class => "form-control" %>
      </div>
​
      <div class="form-group">
        <%= label_tag 'Duration' %>
        <%= text_field_tag 'duration', "#{@event.duration}", :class => "form-control", :rows => "4" %>
      </div>
​
      <div class="form-group">
        <%= label_tag 'Price' %>
        <%= text_field_tag 'price', "#{@event.price}", :class => "form-control", :rows => "4" %>
      </div>
​
      <div class="form-group">
        <%= label_tag 'Location' %>
        <%= text_field_tag 'location', "#{@event.location}", :class => "form-control", :rows => "4" %>
      </div>
​
​
        <%= submit_tag "Edit Event", :class => "btn btn-dark" %>
​
      <% end %>
  </div>
</div>

app/views/events/index.html.erb
<main role="main">
  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-10">
        <% Event.all.each do |event| %>
        <h2>Title: <%= event.title %></h2>
        <p>Descrition: <%= event.description %></p>
        <p>When: <%= event.start_date %></p>
        <p><a class="btn btn-dark" <%= link_to "View more", event_path(event.id) %> &raquo;</a></p>
        <% end %>
    </div>
  </div> <!-- /container -->
</main>

app/views/events/new.html.erb
<div class="row justify-content-center align-items-center" style="margin-top: 10vh; margin-bottom: 10vh;">

            <div class="col-md-8 col-sm-12">

                  <%= form_tag url_for(action: 'create'), method: "post" do %>
                    <div class="form-group">
                      <%= label_tag 'Title' %>
                      <%= text_field_tag 'title', "", :class => "form-control" %>
                    </div>

                    <div class="form-group">
                      <%= label_tag 'Description' %>
                      <%= text_area_tag 'description', "", :class => "form-control", :rows => "4" %>
                    </div>

                     <div class="form-group">
                      <%= label_tag 'Start Date' %>
                      <%= date_field_tag 'start_date', "", :class => "form-control" %>
                    </div>

                    <div class="form-group">
                      <%= label_tag 'Duration' %>
                      <%= text_field_tag 'duration', "", :class => "form-control", :rows => "4" %>
                    </div>

                    <div class="form-group">
                      <%= label_tag 'Price' %>
                      <%= text_field_tag 'price', "", :class => "form-control", :rows => "4" %>
                    </div>

                    <div class="form-group">
                      <%= label_tag 'Location' %>
                      <%= text_field_tag 'location', "", :class => "form-control", :rows => "4" %>
                    </div>


                    <%= submit_tag "Create Event", :class => "btn btn-dark" %>

                  <% end %><br>
                    <% if @event.errors.any? %>
                        <div class="alert alert-danger" role="alert">
                            <h4 class="alert-heading">Crap!</h4>
                            <p><% @event.errors.full_messages.each do |message| %></p>
                            <li><%= message %></li>  
                            <hr>
                            <% end %>
                        </div>
                    <% end %>

            </div>
</div>

app/views/events/show.html.erb
<div class="container my-5">
        <div class="row">
        <div class="col-4">
    </div>
        <div class="col-4">
<div class="card text-center bg-light">
  <div class="card-header">
    👉 EVENT 👈
  </div>
  <div class="card-body">
    <h5 class="card-title font-size large"><%= Event.find(params[:id]).title %> </h5>
    <h5 class="card-title font-size: 10px"><%= Event.find(params[:id]).description %></h5>
    <h5 class="card-title font-size: 10px">Price: <%= Event.find(params[:id]).price %> $</h5>
    <% if current_user == Event.find(params[:id]).admin %>
    <% print %>
    <h6 class="card-title font-size: 10px">Created by: You</h6>
    <% else %>
    <h5 class="card-title font-size small">Created by: <%= Event.find(params[:id]).admin.first_name %></h5>
    <% end %><br>
    <h5 class="card-title font-size: 10px">Where?: <%= Event.find(params[:id]).location %>
     <h5 classe="card-title font-size: 10px">Attandees: <%= Attendence.where(event_id:(params[:id])).count %></h5>
    <h6 class="card-title font-size: 10px"><%= Event.find(params[:id]).created_at %></h6>
    <% if current_user != Event.find(params[:id]).admin %>
    <%= link_to "JOIN THE EVENT !", new_event_attendence_path(params[:id]), :class => "btn btn-outline-info" %>
    <% else %>
    <%= link_to "EDIT YOUR EVENT", edit_event_path(params[:id]), :class => "btn btn-outline-info" %>
    <% end %>
  </div>
  <div class="card-footer text-muted">
   <div class="col-4">
  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Eventbrite-like</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
   <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>
  <body>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" <%= link_to "EVENTBRITE-LIKE", root_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Home", root_path %><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <% if current_user != nil %>
        <a class="nav-link" <%= link_to "Create an event", new_event_path %></a>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <% if current_user %><%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
          <%= button_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %></a>
          <% else %><%= link_to "Sign up", new_user_registration_path, class:"dropdown-item" %>
          <%= link_to "Sign-in", new_user_session_path, class:"dropdown-item" %>
          <% end %>
      </li>
    </ul>
  </div>
</nav>
  <br /><br /><br />
  <%= yield %>
  <footer class="container flex-start">
</footer>
</body>
</html>

app/views/layouts/charge.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container my-5">
    <div class="row">
    <div class="col-4">
</div>
        <div class="col-4">
<div class="card text-center bg-light">
  <div class="card-header">
    👉 My Profile👈
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= current_user.first_name %> <%= current_user.last_name %></h5>
    <h6 class="card-title"><%= current_user.email %></h6>
    <p class="card-text"><%= current_user.created_at %> </p>
  </div>
  <div class="card-footer text-muted">
   <div class="col-4">
  </div>
</div>